import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

import HaikuCreateForm from "./components/HaikuCreateForm";
import HaikuFeed from "./components/HaikuFeed";

export default function Home() {
  const { status } = useSession();

  return (
    <>
      <Head>
        <title>HaikuBook</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#ff82fb] to-[#7069ff]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Haiku<span className="text-[#80e8ff]">Book</span>
          </h1>
          {status === "authenticated" && (
            <>
              <HaikuCreateForm />
              <HaikuFeed />
            </>
          )}

          <div className="flex flex-col items-center gap-2">
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
